"""P-PROC-06's data tables, imported by ops/lib/check-mutate-population.py and read nowhere else.

The tables moved here from the gate in T-0208's merge of origin/main: main's DRIVERS (plan.py, straightline.py)
and this branch's (normalise.py) as a union took the gate to 302 lines against CLAUDE.md's 300-line cap, and a
data table moves before a gate is squeezed. Their meaning is unchanged - the gate's docstring says how each
is read, and the gate's --prove-red runs its shipping entry point over them.
"""

# The WHITELIST of population drivers: any other ops/mutate/*.py with a `__main__` block is a refusal until
# it is classified here (ruling R3).
DRIVERS = ("accounttoken.py", "autopsy.py", "budget.py", "corpusfetch.py", "corpusota.py", "drive.py", "extractadapter.py", "fallback.py", "gates.py", "geometry.py", "guidance.py", "handoff.py",
           "hazards.py", "ledger.py", "menu.py", "search.py", "normalise.py", "onboarding.py", "placeallow.py", "plan.py", "plansheet.py", "retrace.py",
           "roadtrip.py", "routescore.py",
           "loopsheet.py", "saveddrive.py", "savedlist.py", "session.py", "shownhistory.py", "tripsheet.py", "hazardcopy.py",
           "scenic_tags.py",
           "segmentgeometry.py", "segmentscore.py", "straightline.py", "surfacecoverage.py", "surprise.py",
           "telemetry.py", "traffic.py")
PROBES = {"geometry_probe.py": "a probe over geometry.py's population; it declares no subject of its own"}

# The literal floor: every module a driver declares today. Losing one is a refusal (ruling R4 ii).
COVERED_FLOOR = (
    "Sources/ScenicAPIClient/TripNothingPretty.swift", "Sources/ScenicAPIClient/LoopNothingPretty.swift",
    "Sources/ScenicPlanCLI/AutopsyReport.swift", "Sources/ScenicPlanCLI/AutopsyCommand.swift",
    "Sources/ScenicPlanCLI/AutopsyFixture.swift", "Sources/ScenicPlanCLI/AutopsyTerms.swift",
    "Sources/ScenicPlanCLI/AutopsyArguments.swift", "Sources/ScenicPlanCLI/TracingRouteSource.swift",
    "Sources/ScenicKit/Traffic/LearnedCorridorSpeeds.swift", "Sources/ScenicKit/Traffic/HourOfWeek.swift",
    "Sources/ScenicKit/Traffic/CorridorRatio.swift", "Sources/ScenicKit/Traffic/RetimedRoute.swift",
    "Sources/ScenicKit/Traffic/CorridorSlot.swift", "Sources/ScenicKit/Traffic/CorridorCell.swift",
    "Sources/ScenicKit/Traffic/CorridorEdge.swift",
    "Sources/ScenicAPIClient/IdentityHeaders.swift", "Sources/ScenicAPIClient/AccountTokenCandidate.swift",
    "Sources/ScenicAPIClient/URLSessionCorpusFetcher.swift", "Sources/ScenicAPIClient/CorpusDownloadDelegate.swift",
    "Sources/PlaceStore/LaunchCorpus.swift",
    "Sources/PlaceStore/CorpusManifest.swift", "Sources/PlaceStore/CorpusUpdater.swift",
    "Sources/PlaceStore/CorpusSlots.swift", "Sources/PlaceStore/SHA256.swift",
    "Sources/PlaceStore/DriveSessionLock.swift", "Sources/PlaceStore/DriveSessionToken.swift",
    "Sources/ScenicKit/Surprise/Surprise.swift", "Sources/ScenicKit/Surprise/SurpriseCandidate.swift",
    "Sources/ScenicKit/Surprise/SurpriseCategory.swift", "Sources/ScenicKit/Surprise/SurpriseReach.swift",
    "Sources/ScenicKit/Surprise/SurpriseHistory.swift", "Sources/ScenicKit/Surprise/SurpriseFeedback.swift",
    "Sources/ScenicKit/Surprise/SurpriseContext.swift", "Sources/ScenicKit/Surprise/SurpriseReason.swift",
    "Sources/ScenicKit/Surprise/SurprisePick.swift",
    "Sources/ScenicKit/PlanSheet/PlanSheet.swift", "Sources/ScenicKit/PlanSheet/PlanFailureCopy.swift",
    "Sources/ScenicKit/Vehicle/Onboarding.swift", "Sources/ScenicKit/Vehicle/VehicleProfile.swift",
    "Sources/ScenicAPIClient/ClientPlanner.swift",
    "Sources/ScenicKit/Saved/SavedList.swift", "Sources/ScenicKit/Saved/SavedDraft.swift",
    "Sources/ScenicKit/Saved/SavedReplay.swift", "Sources/ScenicKit/Saved/SavedRow.swift",
    "Sources/ScenicAPIClient/LedgerClient.swift", "Sources/ScenicAPIClient/LedgerEntry.swift",
    "Sources/ScenicAPIClient/LedgerReplyReader.swift", "Sources/ScenicKit/Surprise/SurpriseHistoryMerge.swift",
    "Sources/ScenicAPIClient/SearchClient.swift", "Sources/ScenicAPIClient/SearchRequestBody.swift",
    "Sources/ScenicAPIClient/SearchReplyReader.swift", "Sources/ScenicAPIClient/SearchResult.swift",
    "Sources/ScenicAPIClient/AttestClient.swift", "Sources/ScenicAPIClient/AttestReplyReader.swift",
    "Sources/ScenicAPIClient/KeychainWrite.swift", "Sources/ScenicAPIClient/InstallIDDecision.swift",
    "Sources/ScenicAPIClient/SessionRecord.swift", "Sources/ScenicAPIClient/SessionStep.swift",
    "Sources/ScenicAPIClient/SessionStore.swift", "Sources/ScenicAPIClient/LedgerSurpriseSource.swift",
    "Sources/ScenicKit/Surprise/SurpriseShowing.swift",
    "Sources/ScenicKit/Surprise/SurpriseCardHistory.swift", "Sources/ScenicKit/Surprise/SurpriseShownDay.swift",
    "services/etl/etl/accessrule.py", "services/etl/etl/extractadapter.py", "services/etl/etl/fallback.py",
    "services/etl/etl/normalise.py", "services/etl/etl/placeallow.py", "services/etl/etl/proximity.py",
    "services/etl/etl/region_reference.py", "services/etl/etl/scenecheck.py",
    "services/etl/etl/sinuosity.py",
    "services/etl/etl/snap.py", "services/etl/etl/surfacecoverage.py", "services/etl/etl/tagwriter.py",
    "Sources/Handoff/AppleMapsDirections.swift", "Sources/Handoff/HandoffError.swift",
    "Sources/Handoff/StraightLineDistance.swift",
    "Sources/ScenicKit/Drive/DriveSession.swift", "Sources/ScenicKit/Drive/DriveLine.swift",
    "Sources/ScenicKit/Drive/DriveDisplay.swift",
    "Sources/ScenicKit/Drive/DriveSurface.swift", "Sources/ScenicKit/Drive/DriveFix.swift",
    "Sources/ScenicKit/Drive/RerouteRequest.swift",
    "Sources/ScenicKit/TripSheet/TripSheet.swift", "Sources/ScenicKit/TripSheet/TripFailure.swift",
    "Sources/ScenicAPIClient/TripRequestBody.swift", "Sources/ScenicAPIClient/TripReplyReader.swift",
    "Sources/ScenicAPIClient/TripError.swift", "Sources/ScenicAPIClient/TripClient.swift",
    "Sources/ScenicAPIClient/ClientTripPlanner.swift", "Sources/ScenicAPIClient/TripResponse.swift",
    "Sources/ScenicAPIClient/TripResponseDay.swift", "Sources/Handoff/TripDayHandoff.swift",
    "Sources/ScenicKit/LoopSheet/LoopSheet.swift", "Sources/ScenicKit/LoopSheet/LoopFailure.swift",
    "Sources/ScenicAPIClient/LoopRequestBody.swift", "Sources/ScenicAPIClient/LoopReplyReader.swift",
    "Sources/ScenicAPIClient/LoopError.swift", "Sources/ScenicAPIClient/LoopClient.swift",
    "Sources/ScenicAPIClient/ClientLoopPlanner.swift", "Sources/ScenicAPIClient/LoopResponse.swift",
    "Sources/Handoff/LoopHandoff.swift",
    "Sources/ScenicKit/Budget/BudgetError.swift", "Sources/ScenicKit/Budget/BudgetOutcome.swift",
    "Sources/ScenicKit/Budget/LambdaSearch.swift", "Sources/ScenicKit/Gates/ConsideredTags.swift",
    "Sources/ScenicKit/Gates/GateDecision.swift", "Sources/ScenicKit/Gates/GateReason.swift",
    "Sources/ScenicKit/Gates/Gates.swift", "Sources/ScenicKit/Guidance/GuidanceMapping.swift",
    "Sources/ScenicKit/Plan/LambdaCustomModel.swift", "Sources/ScenicKit/Plan/PlanTable.swift",
    "Sources/ScenicKit/Plan/PlanWaypoints.swift", "Sources/ScenicKit/Plan/RouteDifference.swift",
    "Sources/ScenicKit/Plan/RoutePath.swift", "Sources/ScenicKit/Plan/ScenicPlan.swift",
    "Sources/ScenicKit/Plan/ScenicPlanner.swift", "Sources/ScenicPlanCLI/PlanArguments.swift",
    "Sources/ScenicKit/Guidance/GuidanceSign.swift", "Sources/ScenicKit/Hazards/HazardFlag.swift",
    "Sources/ScenicKit/Hazards/HazardStrip.swift", "Sources/ScenicKit/Loop/RetraceDetector.swift",
    "Sources/ScenicKit/Hazards/HazardCopy.swift",
    "Sources/ScenicKit/Scoring/RouteScore.swift", "Sources/ScenicKit/Scoring/SegmentScore.swift",
    "Sources/ScenicKit/Scoring/SegmentTerms.swift",
    "Sources/ScenicKit/Menu/RouteMenu.swift", "Sources/ScenicKit/Menu/MenuRow.swift",
    "Sources/ScenicPlanCLI/MenuArguments.swift", "Sources/ScenicPlanCLI/MenuCommand.swift",
    "Sources/ScenicKit/Menu/RecordedAlternatives.swift",
    "Sources/ScenicKit/RoadTrip/RoadTrip.swift", "Sources/ScenicKit/RoadTrip/RoadTripDay.swift",
    "Sources/ScenicKit/RoadTrip/RoadTripEdge.swift", "Sources/ScenicKit/RoadTrip/RoadTripLimits.swift",
    "Sources/ScenicKit/RoadTrip/RoadTripPlace.swift",
    "Sources/PlaceStore/Segment.swift", "Sources/PlaceStore/SegmentVertex.swift",
    "Sources/PlaceStore/FiveDecimals.swift", "Sources/PlaceStore/SavedMidpoint.swift",
    "Sources/PlaceStore/SavedDrive.swift", "Sources/PlaceStore/SavedDriveResolver.swift",
    "Sources/Telemetry/H3CoordIJK.swift", "Sources/Telemetry/H3FaceProjection.swift",
    "Sources/Telemetry/H3BaseCells.swift", "Sources/Telemetry/H3IndexBuilder.swift",
    "Sources/Telemetry/H3Cell.swift", "Sources/Telemetry/CompletionPercent.swift",
    "Sources/Telemetry/TelemetryDataPoint.swift", "Sources/Telemetry/TelemetryEvent.swift",
)
