// GENERATED by Tests/Fixtures/solar/fetch_oracle.py - do not edit by hand.
// Oracle: US Naval Observatory rstt/oneday, 1-minute resolution, fixed UTC offset per site.
// Fetched 2026-09-07T04:47:27.193201+00:00. sunrise-sunset.org was rejected as an oracle; see the fetcher docstring.
// A nil field means USNO reported no such phenomenon that day (midnight sun / polar night).
import Foundation

struct SolarFixture: Sendable, CustomStringConvertible {
    let name: String; let latitude: Double; let longitude: Double; let date: String
    let sunrise: String?; let sunset: String?; let civilBegin: String?; let civilEnd: String?
    var description: String { name }
}

/// USNO rounds to the minute (+/-30 s) and our model is good to ~35 s.
let solarFixtureToleranceSeconds: Double = 90

let solarFixtures: [SolarFixture] = [
    SolarFixture(name: "sanFrancisco 2026-03-20", latitude: 37.7749, longitude: -122.4194, date: "2026-03-20",
                 sunrise: "2026-03-20T14:13:00Z", sunset: "2026-03-21T02:22:00Z", civilBegin: "2026-03-20T13:47:00Z", civilEnd: "2026-03-21T02:48:00Z"),
    SolarFixture(name: "sanFrancisco 2026-06-21", latitude: 37.7749, longitude: -122.4194, date: "2026-06-21",
                 sunrise: "2026-06-21T12:48:00Z", sunset: "2026-06-22T03:35:00Z", civilBegin: "2026-06-21T12:17:00Z", civilEnd: "2026-06-22T04:06:00Z"),
    SolarFixture(name: "sanFrancisco 2026-09-22", latitude: 37.7749, longitude: -122.4194, date: "2026-09-22",
                 sunrise: "2026-09-22T13:58:00Z", sunset: "2026-09-23T02:06:00Z", civilBegin: "2026-09-22T13:31:00Z", civilEnd: "2026-09-23T02:32:00Z"),
    SolarFixture(name: "sanFrancisco 2026-11-15", latitude: 37.7749, longitude: -122.4194, date: "2026-11-15",
                 sunrise: "2026-11-15T14:50:00Z", sunset: "2026-11-16T00:58:00Z", civilBegin: "2026-11-15T14:22:00Z", civilEnd: "2026-11-16T01:26:00Z"),
    SolarFixture(name: "sanFrancisco 2026-12-21", latitude: 37.7749, longitude: -122.4194, date: "2026-12-21",
                 sunrise: "2026-12-21T15:21:00Z", sunset: "2026-12-22T00:54:00Z", civilBegin: "2026-12-21T14:52:00Z", civilEnd: "2026-12-22T01:24:00Z"),
    SolarFixture(name: "fairbanks 2026-03-20", latitude: 64.8378, longitude: -147.7164, date: "2026-03-20",
                 sunrise: "2026-03-20T15:50:00Z", sunset: "2026-03-21T04:08:00Z", civilBegin: "2026-03-20T15:01:00Z", civilEnd: "2026-03-21T04:57:00Z"),
    SolarFixture(name: "fairbanks 2026-06-21", latitude: 64.8378, longitude: -147.7164, date: "2026-06-21",
                 sunrise: "2026-06-21T10:58:00Z", sunset: "2026-06-22T08:48:00Z", civilBegin: nil, civilEnd: nil),
    SolarFixture(name: "fairbanks 2026-09-22", latitude: 64.8378, longitude: -147.7164, date: "2026-09-22",
                 sunrise: "2026-09-22T15:35:00Z", sunset: "2026-09-23T03:51:00Z", civilBegin: "2026-09-22T14:45:00Z", civilEnd: "2026-09-23T04:40:00Z"),
    SolarFixture(name: "fairbanks 2026-11-15", latitude: 64.8378, longitude: -147.7164, date: "2026-11-15",
                 sunrise: "2026-11-15T18:27:00Z", sunset: "2026-11-16T00:43:00Z", civilBegin: "2026-11-15T17:24:00Z", civilEnd: "2026-11-16T01:46:00Z"),
    SolarFixture(name: "fairbanks 2026-12-21", latitude: 64.8378, longitude: -147.7164, date: "2026-12-21",
                 sunrise: "2026-12-21T19:58:00Z", sunset: "2026-12-21T23:40:00Z", civilBegin: "2026-12-21T18:33:00Z", civilEnd: "2026-12-22T01:05:00Z"),
    SolarFixture(name: "keyWest 2026-03-20", latitude: 24.5551, longitude: -81.78, date: "2026-03-20",
                 sunrise: "2026-03-20T11:31:00Z", sunset: "2026-03-20T23:38:00Z", civilBegin: "2026-03-20T11:08:00Z", civilEnd: "2026-03-21T00:01:00Z"),
    SolarFixture(name: "keyWest 2026-06-21", latitude: 24.5551, longitude: -81.78, date: "2026-06-21",
                 sunrise: "2026-06-21T10:39:00Z", sunset: "2026-06-22T00:19:00Z", civilBegin: "2026-06-21T10:13:00Z", civilEnd: "2026-06-22T00:45:00Z"),
    SolarFixture(name: "keyWest 2026-09-22", latitude: 24.5551, longitude: -81.78, date: "2026-09-22",
                 sunrise: "2026-09-22T11:16:00Z", sunset: "2026-09-22T23:23:00Z", civilBegin: "2026-09-22T10:53:00Z", civilEnd: "2026-09-22T23:46:00Z"),
    SolarFixture(name: "keyWest 2026-11-15", latitude: 24.5551, longitude: -81.78, date: "2026-11-15",
                 sunrise: "2026-11-15T11:43:00Z", sunset: "2026-11-15T22:40:00Z", civilBegin: "2026-11-15T11:19:00Z", civilEnd: "2026-11-15T23:04:00Z"),
    SolarFixture(name: "keyWest 2026-12-21", latitude: 24.5551, longitude: -81.78, date: "2026-12-21",
                 sunrise: "2026-12-21T12:07:00Z", sunset: "2026-12-21T22:44:00Z", civilBegin: "2026-12-21T11:42:00Z", civilEnd: "2026-12-21T23:09:00Z"),
    SolarFixture(name: "honolulu 2026-03-20", latitude: 21.3069, longitude: -157.8583, date: "2026-03-20",
                 sunrise: "2026-03-20T16:35:00Z", sunset: "2026-03-21T04:43:00Z", civilBegin: "2026-03-20T16:13:00Z", civilEnd: "2026-03-21T05:05:00Z"),
    SolarFixture(name: "honolulu 2026-06-21", latitude: 21.3069, longitude: -157.8583, date: "2026-06-21",
                 sunrise: "2026-06-21T15:50:00Z", sunset: "2026-06-22T05:16:00Z", civilBegin: "2026-06-21T15:26:00Z", civilEnd: "2026-06-22T05:41:00Z"),
    SolarFixture(name: "honolulu 2026-09-22", latitude: 21.3069, longitude: -157.8583, date: "2026-09-22",
                 sunrise: "2026-09-22T16:20:00Z", sunset: "2026-09-23T04:27:00Z", civilBegin: "2026-09-22T15:58:00Z", civilEnd: "2026-09-23T04:50:00Z"),
    SolarFixture(name: "honolulu 2026-11-15", latitude: 21.3069, longitude: -157.8583, date: "2026-11-15",
                 sunrise: "2026-11-15T16:42:00Z", sunset: "2026-11-16T03:50:00Z", civilBegin: "2026-11-15T16:19:00Z", civilEnd: "2026-11-16T04:13:00Z"),
    SolarFixture(name: "honolulu 2026-12-21", latitude: 21.3069, longitude: -157.8583, date: "2026-12-21",
                 sunrise: "2026-12-21T17:05:00Z", sunset: "2026-12-22T03:55:00Z", civilBegin: "2026-12-21T16:40:00Z", civilEnd: "2026-12-22T04:19:00Z"),
    SolarFixture(name: "denver 2026-03-20", latitude: 39.7392, longitude: -104.9903, date: "2026-03-20",
                 sunrise: "2026-03-20T13:03:00Z", sunset: "2026-03-21T01:12:00Z", civilBegin: "2026-03-20T12:36:00Z", civilEnd: "2026-03-21T01:39:00Z"),
    SolarFixture(name: "denver 2026-06-21", latitude: 39.7392, longitude: -104.9903, date: "2026-06-21",
                 sunrise: "2026-06-21T11:32:00Z", sunset: "2026-06-22T02:31:00Z", civilBegin: "2026-06-21T11:00:00Z", civilEnd: "2026-06-22T03:04:00Z"),
    SolarFixture(name: "denver 2026-09-22", latitude: 39.7392, longitude: -104.9903, date: "2026-09-22",
                 sunrise: "2026-09-22T12:48:00Z", sunset: "2026-09-23T00:57:00Z", civilBegin: "2026-09-22T12:21:00Z", civilEnd: "2026-09-23T01:24:00Z"),
    SolarFixture(name: "denver 2026-11-15", latitude: 39.7392, longitude: -104.9903, date: "2026-11-15",
                 sunrise: "2026-11-15T13:45:00Z", sunset: "2026-11-15T23:44:00Z", civilBegin: "2026-11-15T13:16:00Z", civilEnd: "2026-11-16T00:13:00Z"),
    SolarFixture(name: "denver 2026-12-21", latitude: 39.7392, longitude: -104.9903, date: "2026-12-21",
                 sunrise: "2026-12-21T14:18:00Z", sunset: "2026-12-21T23:39:00Z", civilBegin: "2026-12-21T13:47:00Z", civilEnd: "2026-12-22T00:09:00Z"),
    SolarFixture(name: "newYork 2026-03-20", latitude: 40.7128, longitude: -74.006, date: "2026-03-20",
                 sunrise: "2026-03-20T10:59:00Z", sunset: "2026-03-20T23:08:00Z", civilBegin: "2026-03-20T10:32:00Z", civilEnd: "2026-03-20T23:36:00Z"),
    SolarFixture(name: "newYork 2026-06-21", latitude: 40.7128, longitude: -74.006, date: "2026-06-21",
                 sunrise: "2026-06-21T09:25:00Z", sunset: "2026-06-22T00:31:00Z", civilBegin: "2026-06-21T08:52:00Z", civilEnd: "2026-06-22T01:04:00Z"),
    SolarFixture(name: "newYork 2026-09-22", latitude: 40.7128, longitude: -74.006, date: "2026-09-22",
                 sunrise: "2026-09-22T10:44:00Z", sunset: "2026-09-22T22:53:00Z", civilBegin: "2026-09-22T10:16:00Z", civilEnd: "2026-09-22T23:20:00Z"),
    SolarFixture(name: "newYork 2026-11-15", latitude: 40.7128, longitude: -74.006, date: "2026-11-15",
                 sunrise: "2026-11-15T11:43:00Z", sunset: "2026-11-15T21:38:00Z", civilBegin: "2026-11-15T11:14:00Z", civilEnd: "2026-11-15T22:07:00Z"),
    SolarFixture(name: "newYork 2026-12-21", latitude: 40.7128, longitude: -74.006, date: "2026-12-21",
                 sunrise: "2026-12-21T12:17:00Z", sunset: "2026-12-21T21:32:00Z", civilBegin: "2026-12-21T11:46:00Z", civilEnd: "2026-12-21T22:03:00Z"),
    SolarFixture(name: "seattle 2026-03-20", latitude: 47.6062, longitude: -122.3321, date: "2026-03-20",
                 sunrise: "2026-03-20T14:12:00Z", sunset: "2026-03-21T02:22:00Z", civilBegin: "2026-03-20T13:41:00Z", civilEnd: "2026-03-21T02:53:00Z"),
    SolarFixture(name: "seattle 2026-06-21", latitude: 47.6062, longitude: -122.3321, date: "2026-06-21",
                 sunrise: "2026-06-21T12:12:00Z", sunset: "2026-06-22T04:11:00Z", civilBegin: "2026-06-21T11:31:00Z", civilEnd: "2026-06-22T04:52:00Z"),
    SolarFixture(name: "seattle 2026-09-22", latitude: 47.6062, longitude: -122.3321, date: "2026-09-22",
                 sunrise: "2026-09-22T13:56:00Z", sunset: "2026-09-23T02:07:00Z", civilBegin: "2026-09-22T13:26:00Z", civilEnd: "2026-09-23T02:37:00Z"),
    SolarFixture(name: "seattle 2026-11-15", latitude: 47.6062, longitude: -122.3321, date: "2026-11-15",
                 sunrise: "2026-11-15T15:15:00Z", sunset: "2026-11-16T00:33:00Z", civilBegin: "2026-11-15T14:41:00Z", civilEnd: "2026-11-16T01:06:00Z"),
    SolarFixture(name: "seattle 2026-12-21", latitude: 47.6062, longitude: -122.3321, date: "2026-12-21",
                 sunrise: "2026-12-21T15:55:00Z", sunset: "2026-12-22T00:20:00Z", civilBegin: "2026-12-21T15:19:00Z", civilEnd: "2026-12-22T00:56:00Z"),
]
