#!/usr/bin/env python3
"""Fetch solar-event fixtures from an EXTERNAL oracle so the tests cannot encode what we already believe.

PRIMARY ORACLE: US Naval Observatory, https://aa.usno.navy.mil/api/rstt/oneday
  The authoritative US source. Times are HH:MM (1-minute resolution) in the fixed UTC offset we pass as `tz`,
  so the conversion back to UTC is exact and DST never enters. We pass tz = round(longitude / 15) so USNO's
  "day" is the same local solar day our SolarEvents model uses.

REJECTED ORACLE: sunrise-sunset.org. Its civil twilight agrees with USNO to ~20 s, but its sunrise/sunset
  disagree with USNO by 84 s (Key West, San Francisco) to 343 s (Fairbanks) — it evidently uses a different
  rise/set zenith. Our own values match USNO to within 34 s at every site including Fairbanks, so the earlier
  fixtures were wrong, not the code. Kept in oracle.json under "rejected_secondary" as the evidence trail.

TOLERANCE: USNO rounds to the minute (±30 s) and our model is good to ~35 s, so the test tolerance is 90 s.

Re-run only deliberately. Writes:
  Tests/Fixtures/solar/oracle.json            raw responses + provenance
  Tests/ScenicKitTests/SolarFixtures.swift    generated Swift literals used by SolarFixtureTests
"""
import datetime as dt
import json
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
UA = "scenic-drive-fixtures/1 (+https://github.com/phineasfritsch/scenic_drive)"

PLACES = {
    "sanFrancisco": (37.7749, -122.4194),
    "fairbanks": (64.8378, -147.7164),
    "keyWest": (24.5551, -81.7800),
    "honolulu": (21.3069, -157.8583),
    "denver": (39.7392, -104.9903),
    "newYork": (40.7128, -74.0060),
    "seattle": (47.6062, -122.3321),
}
DATES = ["2026-03-20", "2026-06-21", "2026-09-22", "2026-11-15", "2026-12-21"]
PHEN = {"Rise": "sunrise", "Set": "sunset", "Begin Civil Twilight": "civilBegin", "End Civil Twilight": "civilEnd"}


def get(url):
    req = urllib.request.Request(url, headers={"user-agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)


def main():
    out = {
        "fetched_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        "primary": "https://aa.usno.navy.mil/api/rstt/oneday (US Naval Observatory, 1-minute resolution)",
        "rejected_secondary": "sunrise-sunset.org - rise/set disagreed with USNO by 84-343 s; see module docstring",
        "tolerance_seconds": 90,
        "places": PLACES,
        "cases": [],
    }
    for place, (lat, lon) in PLACES.items():
        tz = int(round(lon / 15))  # fixed offset, no DST; makes USNO's day == our local solar day
        for date in DATES:
            d = get(f"https://aa.usno.navy.mil/api/rstt/oneday?date={date}&coords={lat},{lon}&tz={tz}")
            sundata = d.get("properties", {}).get("data", {}).get("sundata", [])
            if not sundata:
                print(f"no sundata for {place} {date}", file=sys.stderr)
                return 1
            y, m, dd = map(int, date.split("-"))
            local_midnight = dt.datetime(y, m, dd, tzinfo=dt.timezone(dt.timedelta(hours=tz)))
            events = {}
            for p in sundata:
                key = PHEN.get(p["phen"])
                if not key:
                    continue
                hh, mm = map(int, p["time"].split(":"))
                events[key] = (local_midnight + dt.timedelta(hours=hh, minutes=mm)).astimezone(dt.timezone.utc)
            case = {"place": place, "lat": lat, "lon": lon, "date": date, "tz": tz,
                    "phenomena": {k: v.strftime("%Y-%m-%dT%H:%M:%SZ") for k, v in events.items()}}
            out["cases"].append(case)
            got = " ".join(f"{k}={v:%H:%M}" for k, v in sorted(events.items()))
            print(f"{place:13s} {date} tz{tz:+03d}  {got}")

    (ROOT / "Tests/Fixtures/solar/oracle.json").write_text(json.dumps(out, indent=2), encoding="utf-8", newline="\n")

    lines = [
        "// GENERATED by Tests/Fixtures/solar/fetch_oracle.py - do not edit by hand.",
        "// Oracle: US Naval Observatory rstt/oneday, 1-minute resolution, fixed UTC offset per site.",
        f"// Fetched {out['fetched_at']}. sunrise-sunset.org was rejected as an oracle; see the fetcher docstring.",
        "// A nil field means USNO reported no such phenomenon that day (midnight sun / polar night).",
        "import Foundation",
        "",
        "struct SolarFixture: Sendable, CustomStringConvertible {",
        "    let name: String; let latitude: Double; let longitude: Double; let date: String",
        "    let sunrise: String?; let sunset: String?; let civilBegin: String?; let civilEnd: String?",
        "    var description: String { name }",
        "}",
        "",
        "/// USNO rounds to the minute (+/-30 s) and our model is good to ~35 s.",
        "let solarFixtureToleranceSeconds: Double = 90",
        "",
        "let solarFixtures: [SolarFixture] = [",
    ]

    def lit(case, key):
        v = case["phenomena"].get(key)
        return f'"{v}"' if v else "nil"

    for c in out["cases"]:
        lines.append(f'    SolarFixture(name: "{c["place"]} {c["date"]}", latitude: {c["lat"]}, longitude: {c["lon"]}, date: "{c["date"]}",')
        lines.append(f'                 sunrise: {lit(c, "sunrise")}, sunset: {lit(c, "sunset")}, civilBegin: {lit(c, "civilBegin")}, civilEnd: {lit(c, "civilEnd")}),')
    lines.append("]")
    (ROOT / "Tests/ScenicKitTests/SolarFixtures.swift").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {len(out['cases'])} fixtures")
    return 0


if __name__ == "__main__":
    sys.exit(main())
