#!/usr/bin/env python3
"""Writes Tests/ScenicKitTests/Traffic/CorridorCellReference.swift from h3-py (T-0325 R1).

    python Tests/Fixtures/t0325/gen_corridor_cells.py   # h3-py 4.1.2 (pip install h3==4.1.2)

Every point is answered by uber/h3's own latlng_to_cell at resolution 5 and 8; the Swift table is the oracle the
ScenicKit copy of Telemetry's port is compared to by full equality. Points: Los Angeles and Bay Area drives, the 12
pentagon centres at both resolutions, the poles, the antimeridian and the range bounds, and 200 seeded random
points. Doubles are written with repr, which Swift parses to the same bits.
"""
import pathlib
import random

import h3

assert h3.__version__ == "4.1.2", h3.__version__

OUT = pathlib.Path(__file__).resolve().parents[2] / "ScenicKitTests" / "Traffic" / "CorridorCellReference.swift"

POINTS = [
    (34.0522, -118.2437), (34.0928, -118.6064), (34.0901, -118.6720), (34.0259, -118.7798), (34.1184, -118.3004),
    (33.7701, -118.1937), (34.2203, -118.2398), (34.3917, -118.5426), (37.7749, -122.4194), (37.8044, -122.2712),
    (37.4419, -122.1430), (37.8716, -122.2727), (37.9235, -122.5965), (37.3382, -121.8863),
    (90.0, 0.0), (-90.0, 0.0), (90.0, 180.0), (-90.0, -180.0), (0.0, 180.0), (0.0, -180.0), (45.0, 180.0),
    (-45.0, -180.0), (0.0, 0.0), (89.999999, 179.999999), (-89.999999, -179.999999),
]
for res in (5, 8):
    for cell in sorted(h3.get_pentagons(res)):
        POINTS.append(h3.cell_to_latlng(cell))
rng = random.Random(325)
for _ in range(200):
    POINTS.append((rng.uniform(-90.0, 90.0), rng.uniform(-180.0, 180.0)))

rows = []
for lat, lon in POINTS:
    r5 = int(h3.latlng_to_cell(lat, lon, 5), 16)
    r8 = int(h3.latlng_to_cell(lat, lon, 8), 16)
    rows.append("        (%r, %r, 0x%015x, 0x%015x)," % (float(lat), float(lon), r5, r8))

OUT.write_text("\n".join([
    "/// GENERATED by Tests/Fixtures/t0325/gen_corridor_cells.py from h3-py %s - do not edit (T-0325 R1)." % h3.__version__,
    "/// Each row: a point in degrees and uber/h3's latlng_to_cell at resolution 5 and at resolution 8.",
    "enum CorridorCellReference {",
    "    static let rows: [(latitude: Double, longitude: Double, res5: UInt64, res8: UInt64)] = [",
    *rows,
    "    ]",
    "}",
    "",
]), newline="\n")
print("wrote %d rows to %s" % (len(rows), OUT))
